; ============================================================
; WebView Bridge v3.9 — NSIS Installer
; ============================================================
;
; Build:  installer\build_installer.bat
; Requires: NSIS 3.x (Unicode), PowerShell 5.1+
;
; Japanese font handling:
;   - Unicode true (必須 — ANSI版では日本語が文字化け)
;   - MUI_LANGUAGE "Japanese"
;   - カスタムページで Yu Gothic UI フォントを明示指定

Unicode true
SetCompressor /SOLID lzma
ManifestDPIAware true

!include "MUI2.nsh"
!include "nsDialogs.nsh"
!include "LogicLib.nsh"
!include "FileFunc.nsh"
!include "WinMessages.nsh"

; ============================================================
; Product Info
; ============================================================

!define PRODUCT_NAME    "WebView Bridge"
; PRODUCT_VERSION is passed via /D from build_nsis.ps1 (sourced from Cargo.toml)
!ifndef PRODUCT_VERSION
  !error "PRODUCT_VERSION not defined — run via build_nsis.ps1"
!endif
!define PRODUCT_EXE     "webview-bridge-rust.exe"
!define PRODUCT_PUBLISHER "mhit"
!define PRODUCT_URL     "https://github.com/mhit/webview-bridge"
!define UNINST_KEY      "Software\Microsoft\Windows\CurrentVersion\Uninstall\WebViewBridge"
!define RUN_KEY         "Software\Microsoft\Windows\CurrentVersion\Run"
!define DATA_DIR        "$APPDATA\webview-bridge"

; ============================================================
; UI — Icons & Bitmaps
; ============================================================

!define MUI_ICON   "..\docs\img\icon.ico"
!define MUI_UNICON "..\docs\img\icon.ico"

; Header bitmap (150x57) — generated by build script
!ifdef HEADER_BMP
  !define MUI_HEADERIMAGE
  !define MUI_HEADERIMAGE_BITMAP "${HEADER_BMP}"
  !define MUI_HEADERIMAGE_RIGHT
!endif

; Welcome/Finish side bitmap (164x314) — generated by build script
!ifdef WELCOME_BMP
  !define MUI_WELCOMEFINISHPAGE_BITMAP "${WELCOME_BMP}"
!endif

!define MUI_ABORTWARNING
!define MUI_ABORTWARNING_TEXT "インストールを中止しますか？"

; Japanese font fix — hook into MUI's onGUIInit
!define MUI_CUSTOMFUNCTION_GUIINIT JapaneseFontFix
!define MUI_CUSTOMFUNCTION_UNGUIINIT un.JapaneseFontFix

; ============================================================
; Finish Page — Launch & Startup checkboxes
; ============================================================

!define MUI_FINISHPAGE_RUN "$INSTDIR\${PRODUCT_EXE}"
!define MUI_FINISHPAGE_RUN_TEXT "${PRODUCT_NAME} を起動する"

; Repurpose "Show ReadMe" checkbox for startup registration
!define MUI_FINISHPAGE_SHOWREADME ""
!define MUI_FINISHPAGE_SHOWREADME_NOTCHECKED
!define MUI_FINISHPAGE_SHOWREADME_TEXT "Windows 起動時に自動起動する"
!define MUI_FINISHPAGE_SHOWREADME_FUNCTION RegisterStartup

; ============================================================
; Pages
; ============================================================

; --- Installer ---
!insertmacro MUI_PAGE_WELCOME
!insertmacro MUI_PAGE_LICENSE "..\LICENSE"
!insertmacro MUI_PAGE_DIRECTORY
!insertmacro MUI_PAGE_INSTFILES
!insertmacro MUI_PAGE_FINISH

; --- Uninstaller ---
!insertmacro MUI_UNPAGE_CONFIRM
UninstPage custom un.DataCleanupPage un.DataCleanupPageLeave
!insertmacro MUI_UNPAGE_INSTFILES

; ============================================================
; Languages
; ============================================================

!insertmacro MUI_LANGUAGE "Japanese"
!insertmacro MUI_LANGUAGE "English"

; ============================================================
; Variables
; ============================================================

Var DeleteDataCheckbox
Var DeleteDataState
Var WebView2Version

; ============================================================
; Installer Attributes
; ============================================================

Name "${PRODUCT_NAME} ${PRODUCT_VERSION}"
OutFile "..\dist\WebViewBridge-${PRODUCT_VERSION}-Setup.exe"
InstallDir "$PROGRAMFILES64\${PRODUCT_NAME}"
InstallDirRegKey HKLM "${UNINST_KEY}" "InstallLocation"
RequestExecutionLevel admin

; ============================================================
; Japanese Font Fix — called via MUI_CUSTOMFUNCTION_GUIINIT
; ============================================================

Function JapaneseFontFix
  System::Call 'kernel32::GetUserDefaultUILanguage() i .r0'
  ${If} $0 == 1041
    CreateFont $1 "Yu Gothic UI" 9 400
    SendMessage $HWNDPARENT ${WM_SETFONT} $1 1
  ${EndIf}
FunctionEnd

Function un.JapaneseFontFix
  System::Call 'kernel32::GetUserDefaultUILanguage() i .r0'
  ${If} $0 == 1041
    CreateFont $1 "Yu Gothic UI" 9 400
    SendMessage $HWNDPARENT ${WM_SETFONT} $1 1
  ${EndIf}
FunctionEnd

; ============================================================
; Helper: Check & Install WebView2 Runtime via winget
; ============================================================

Function CheckAndInstallWebView2
  ; Check 64-bit registry first
  ReadRegStr $WebView2Version HKLM \
    "SOFTWARE\WOW6432Node\Microsoft\EdgeUpdate\Clients\{F3017226-FE2A-4295-8BDF-00C3A9A7E4C5}" \
    "pv"
  ${If} $WebView2Version != ""
    DetailPrint "WebView2 Runtime detected: $WebView2Version"
    Return
  ${EndIf}

  ; Check native registry
  ReadRegStr $WebView2Version HKLM \
    "SOFTWARE\Microsoft\EdgeUpdate\Clients\{F3017226-FE2A-4295-8BDF-00C3A9A7E4C5}" \
    "pv"
  ${If} $WebView2Version != ""
    DetailPrint "WebView2 Runtime detected: $WebView2Version"
    Return
  ${EndIf}

  ; WebView2 not found — try winget
  DetailPrint "WebView2 Runtime not found. Installing via winget..."
  nsExec::ExecToLog 'winget install --id Microsoft.EdgeWebView2Runtime --accept-source-agreements --accept-package-agreements --silent'
  Pop $0
  ${If} $0 == 0
    DetailPrint "WebView2 Runtime installed successfully."
    Return
  ${EndIf}

  ; winget failed — show manual download message
  MessageBox MB_OK|MB_ICONINFORMATION \
    "WebView2 Runtime のインストールに失敗しました。$\r$\n$\r$\n\
    以下の URL から手動でインストールしてください:$\r$\n\
    https://developer.microsoft.com/ja-jp/microsoft-edge/webview2/$\r$\n$\r$\n\
    WebView2 Runtime がないと ${PRODUCT_NAME} は動作しません。"
FunctionEnd

; ============================================================
; Installer Section
; ============================================================

Section "Install" SecInstall
  ; --- Check & Install WebView2 Runtime ---
  Call CheckAndInstallWebView2

  SetOutPath "$INSTDIR"

  ; --- Main executable ---
  File "..\target\release\${PRODUCT_EXE}"

  ; --- CLI executable ---
  File /oname=wb.exe "..\target\release\wb.exe"

  ; --- Icon ---
  SetOutPath "$INSTDIR"
  File /oname=icon.ico "..\docs\img\icon.ico"

  ; --- Documentation ---
  SetOutPath "$INSTDIR\docs"
  File "..\docs\QUICK_START.md"
  File "..\docs\MCP_TOOLS.md"
  File "..\docs\ARCHITECTURE.md"
  File "..\docs\API.md"

  ; --- Sample config (only if not already exists) ---
  SetOutPath "$INSTDIR"
  IfFileExists "${DATA_DIR}\config.toml" +2 0
  Call CreateSampleConfig

  ; --- Uninstaller ---
  WriteUninstaller "$INSTDIR\Uninstall.exe"

  ; --- Start Menu ---
  CreateDirectory "$SMPROGRAMS\${PRODUCT_NAME}"
  CreateShortcut "$SMPROGRAMS\${PRODUCT_NAME}\${PRODUCT_NAME}.lnk" \
    "$INSTDIR\${PRODUCT_EXE}" "" "$INSTDIR\icon.ico"
  CreateShortcut "$SMPROGRAMS\${PRODUCT_NAME}\アンインストール.lnk" \
    "$INSTDIR\Uninstall.exe" "" "$INSTDIR\icon.ico"

  ; --- Desktop shortcut ---
  CreateShortcut "$DESKTOP\${PRODUCT_NAME}.lnk" \
    "$INSTDIR\${PRODUCT_EXE}" "" "$INSTDIR\icon.ico"

  ; --- Add/Remove Programs ---
  WriteRegStr   HKLM "${UNINST_KEY}" "DisplayName"     "${PRODUCT_NAME}"
  WriteRegStr   HKLM "${UNINST_KEY}" "DisplayVersion"  "${PRODUCT_VERSION}"
  WriteRegStr   HKLM "${UNINST_KEY}" "Publisher"        "${PRODUCT_PUBLISHER}"
  WriteRegStr   HKLM "${UNINST_KEY}" "URLInfoAbout"     "${PRODUCT_URL}"
  WriteRegStr   HKLM "${UNINST_KEY}" "UninstallString"  "$\"$INSTDIR\Uninstall.exe$\""
  WriteRegStr   HKLM "${UNINST_KEY}" "InstallLocation"  "$INSTDIR"
  WriteRegStr   HKLM "${UNINST_KEY}" "DisplayIcon"      "$INSTDIR\icon.ico"
  WriteRegDWORD HKLM "${UNINST_KEY}" "NoModify" 1
  WriteRegDWORD HKLM "${UNINST_KEY}" "NoRepair" 1

  ; Installed size
  ${GetSize} "$INSTDIR" "/S=0K" $0 $1 $2
  IntFmt $0 "0x%08X" $0
  WriteRegDWORD HKLM "${UNINST_KEY}" "EstimatedSize" $0

  ; --- Add to system PATH (for wb CLI) ---
  nsExec::ExecToLog 'powershell -NoProfile -Command "\
    $$p = [Environment]::GetEnvironmentVariable(''Path'',''Machine''); \
    if ($$p -notlike ''*$INSTDIR*'') { \
      [Environment]::SetEnvironmentVariable(''Path'', $$p + '';$INSTDIR'', ''Machine'') \
    }"'
SectionEnd

; ============================================================
; Helper: Create sample config.toml in %APPDATA%
; ============================================================

Function CreateSampleConfig
  CreateDirectory "${DATA_DIR}"
  FileOpen  $0 "${DATA_DIR}\config.toml" w
  FileWrite $0 "[server]$\r$\n"
  FileWrite $0 "bind = $\"0.0.0.0$\"$\r$\n"
  FileWrite $0 "port = 9400$\r$\n"
  FileWrite $0 "max_sessions = 10$\r$\n"
  FileWrite $0 "$\r$\n"
  FileWrite $0 "[ai]$\r$\n"
  FileWrite $0 "enabled = false$\r$\n"
  FileWrite $0 "provider = $\"ollama$\"$\r$\n"
  FileWrite $0 "model = $\"gemma3:12b$\"$\r$\n"
  FileWrite $0 "# api_key = $\"your-gemini-key$\"$\r$\n"
  FileWrite $0 "$\r$\n"
  FileWrite $0 "[session]$\r$\n"
  FileWrite $0 "# default_ttl_hours = 168$\r$\n"
  FileWrite $0 "$\r$\n"
  FileWrite $0 "[media]$\r$\n"
  FileWrite $0 "# download_dir = $\"downloads$\"$\r$\n"
  FileClose $0
FunctionEnd

; ============================================================
; Helper: Register startup
; ============================================================

Function RegisterStartup
  WriteRegStr HKCU "${RUN_KEY}" "${PRODUCT_NAME}" '"$INSTDIR\${PRODUCT_EXE}"'
FunctionEnd

; ============================================================
; Uninstaller — Data Cleanup Page (nsDialogs)
; ============================================================

Function un.DataCleanupPage
  ; Japanese font for this custom page
  nsDialogs::Create 1018
  Pop $0
  ${If} $0 == error
    Abort
  ${EndIf}

  ; Set font
  CreateFont $1 "Yu Gothic UI" 10 400

  ; Description label
  ${NSD_CreateLabel} 0 0 100% 50u \
    "セッションデータの削除$\r$\n$\r$\n\
    以下のフォルダにはCookie・ログイン状態・config.toml などの$\r$\n\
    セッションデータが保存されています:$\r$\n$\r$\n\
    ${DATA_DIR}"
  Pop $2
  SendMessage $2 ${WM_SETFONT} $1 1

  ; Checkbox
  ${NSD_CreateCheckbox} 0 65u 100% 15u \
    "セッションデータ・設定ファイルも削除する"
  Pop $DeleteDataCheckbox
  SendMessage $DeleteDataCheckbox ${WM_SETFONT} $1 1

  ; Warning
  ${NSD_CreateLabel} 15u 85u 100% 30u \
    "※ チェックすると Cookie やログイン状態が失われます"
  Pop $3
  SendMessage $3 ${WM_SETFONT} $1 1
  SetCtlColors $3 "CC0000" transparent

  nsDialogs::Show
FunctionEnd

Function un.DataCleanupPageLeave
  ${NSD_GetState} $DeleteDataCheckbox $DeleteDataState
FunctionEnd

; ============================================================
; Uninstaller Section
; ============================================================

Section "Uninstall"
  ; --- Data directory cleanup (if user checked the box) ---
  ${If} $DeleteDataState == ${BST_CHECKED}
    RMDir /r "${DATA_DIR}"
  ${EndIf}

  ; --- Remove startup entry ---
  DeleteRegValue HKCU "${RUN_KEY}" "${PRODUCT_NAME}"

  ; --- Remove files ---
  Delete "$INSTDIR\${PRODUCT_EXE}"
  Delete "$INSTDIR\wb.exe"
  Delete "$INSTDIR\icon.ico"
  Delete "$INSTDIR\Uninstall.exe"
  RMDir /r "$INSTDIR\docs"
  RMDir  "$INSTDIR"

  ; --- Remove from system PATH ---
  nsExec::ExecToLog 'powershell -NoProfile -Command "\
    $$p = [Environment]::GetEnvironmentVariable(''Path'',''Machine''); \
    $$n = ($$p -split '';'' | Where-Object { $$_ -ne ''$INSTDIR'' }) -join '';''; \
    if ($$n -ne $$p) { [Environment]::SetEnvironmentVariable(''Path'', $$n, ''Machine'') }"'

  ; --- Remove shortcuts ---
  Delete "$DESKTOP\${PRODUCT_NAME}.lnk"
  Delete "$SMPROGRAMS\${PRODUCT_NAME}\*.lnk"
  RMDir  "$SMPROGRAMS\${PRODUCT_NAME}"

  ; --- Remove registry ---
  DeleteRegKey HKLM "${UNINST_KEY}"
SectionEnd
